name       : haskell-monadrandom
version    : 0.5.1
release    : 3
source     :
    - https://hackage.haskell.org/package/MonadRandom-0.5.1/MonadRandom-0.5.1.tar.gz : 9e3f0f92807285302036dc504066ae6d968c8b0b4c25d9360888f31fe1730d87
license    : BSD-3-Clause
component  : programming.haskell
summary    : Support for computations which consume random values.
description: |
    Support for computations which consume random values.
builddeps  :
    - haskell-cabal-install
    - haskell-fail
    - haskell-mtl
    - haskell-primitive
    - haskell-transformers-compat
    - haskell-random
setup      : |
    sed -i "s|<0.6|<0.7|g" MonadRandom.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
