name       : haskell-monadrandom
version    : 0.4.2.3
release    : 2
source     :
    - http://hackage.haskell.org/package/MonadRandom-0.4.2.3/MonadRandom-0.4.2.3.tar.gz : de40b12a70ec6425a9e54b33e2ac652e14d7c005a3b46d701d1e5696b98636c0
license    : BSD-3-Clause
component  : programming.haskell
summary    : Support for computations which consume random values.
description: |
    Support for computations which consume random values.
builddeps  :
    - haskell-cabal-install
    - haskell-fail
    - haskell-transformers-compat
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
