name       : haskell-monadrandom
version    : 0.5.1.2
release    : 5
source     :
    - https://hackage.haskell.org/package/MonadRandom-0.5.1.2/MonadRandom-0.5.1.2.tar.gz : 776f0e69ddea30c9e819f1cd75249377b7fc6f7c8181b90e72ec9c7bc7e33448
license    : BSD-3-Clause
component  : programming.haskell
summary    : Support for computations which consume random values.
description: |
    Support for computations which consume random values.
builddeps  :
    - haskell-cabal-install
    - haskell-primitive-devel
    - haskell-transformers-compat-devel
    - haskell-random-devel
rundeps    :
    - devel :
        - haskell-primitive-devel
        - haskell-transformers-compat-devel
        - haskell-random-devel
networking : yes
setup      : |
    sed -i "s|<0.6|<0.7|g" MonadRandom.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
