name       : haskell-monadrandom
version    : 0.5.1
release    : 1
source     :
    - http://hackage.haskell.org/package/MonadRandom-0.5.1/MonadRandom-0.5.1.tar.gz : 9e3f0f92807285302036dc504066ae6d968c8b0b4c25d9360888f31fe1730d87
license    : BSD-3-Clause
component  : programming.haskell
summary    : Support for computations which consume random values. 
description: |
    Support for computations which consume random values. 
builddeps  :
    - haskell-cabal-install
    - haskell-fail
    - haskell-primitive
    - haskell-transformers-compat
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
